phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # install all dependencies
      - npm install
  build:
    commands:
      #- npm run lint

      # npm install yarn globally for mfe deployment #important
      - |
        if [ "${ENVIRONMENT}" = "develop" ]; then
          npm run build-dev
        else if [ "${ENVIRONMENT}" = "staging" ]; then
          npm run build-stage
        else
          npm run build-prod
        fi
  post_build:
    commands:
      - aws s3 sync ./dist s3://${BUCKETURL}
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONTID} --paths "/*"
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: 'dist'
cache:
  paths:
    - ./node_modules/**/*